---
title             : "Supplement to 'Fundamental errors of data collection & validation undermine claims of 'Ideological Intensification' made by the National Association of Scholars'"
shorttitle        : "Flawed data validation by the NAS"

author: 
  - name          : "Emilio M. Bruna"
    affiliation   : "1,2"
#    address       : "Department of Wildlife Ecology and Conservation, University of Florida, PO Box 110430, Gainesville, FL 32611-0430, USA"
    email         : "embruna@ufl.edu"
    # role:
    #   - Methodology
    #   - Data curation
    #   - Investigation
    #   - Funding acquisition
    #   - Conceptualization
    #   - Formal analysis
    #   - Methodology
    #   - Project administration
    #   - Resources
    #   - Software
    #   - Supervision
    #   - Validation
    #   - Visualization
    #   - Writing original draft

affiliation:
  - id            : "1"
    institution   : "Department of Wildlife Ecology and Conservation, University of Florida, PO Box 110430, Gainesville, FL 32611-0430, USA"
  - id            : "2"
    institution   : "Center for Latin American Studies, University of Florida, PO Box 115530, Gainesville, FL 32611-5530, USA"

authornote: All code and data used in this analysis are available at https://github.com/embruna/quantdei_nas. 

# 
# abstract: |
#   Abstract of the paper.

keywords          : "Up,to,eight,keywords"
wordcount         : "X"

bibliography      : "NAS_response.bib"

floatsintext      : no
figurelist        : yes
tablelist         : no
footnotelist      : no
numbersections    : no
linenumbers       : yes
mask              : no
draft             : no
# replace_ampersands: yes

# classoption       : "man, donotrepeattitle" # suppresses title on 1st page of MS
classoption       : "donotrepeattitle" # suppresses title on 1st page of MS
mainfont: Times New Roman
fontsize: 12pt
csl: "science.csl"
fig_caption: yes
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{} # remove page number bottom of the page
- \fancyhead[L]{E. M. Bruna, (Supplement)}
- \fancyhead[R]{p. \thepage}
- \usepackage{setspace}
- \usepackage{parskip} 
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \usepackage{caption}                            
- \DeclareCaptionLabelFormat{Sformat}{#1 S#2}     
- \captionsetup[table]{labelformat=Sformat}  
- \captionsetup[figure]{labelformat=Sformat}  
# keep_tex: true
# output: papaja::apa6_pdf
      
output: pdf_document
keep_tex: true
# 
# header-includes:
#   - \raggedbottom
#   - \usepackage{endfloat} #[nomarkers] excludes the {insert figure x around here] from main text. The others exclude the list of tables and figures. https://cs.brown.edu/about/system/managed/latex/doc/endfloat.pdf
#   - \usepackage{setspace}\singlespacing
#   - \usepackage{lineno}
#   - \linenumbers
#   - \usepackage{tabu}
#   - \usepackage{pdflscape}
#   # - \usepackage{lscape}
#   - \newcommand{\blandscape}{\begin{landscape}}
#   - \newcommand{\elandscape}{\end{landscape}}

---

```{r setup, include = FALSE}
library("papaja")
r_refs("NAS_response.bib")
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)
library(tidyverse)
library(gridExtra)
library(kableExtra)
library(egg)
library(magick)
```

```{r GlobalOptions, include=FALSE}
options(knitr.duplicate.label = 'allow')
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
# knitr::opts_chunk$set(fig.pos = 'h')
```
\renewcommand{\arraystretch}{1}

```{r cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE}
knitr::opts_chunk$set(echo = FALSE)
twitter_notdei<-read_csv("./error_analysis_bruna/validation_output/twitter_notdei.csv",col_types = cols())
twitter_notdei_summary<-read_csv("./error_analysis_bruna/validation_output/twitter_notdei_summary.csv",col_types = cols())

total_tweets_reviewed<-twitter_notdei_summary %>%
  select(total_tweets_reviewed) %>%
  slice(1)

total_tweets_clean<-twitter_notdei_summary %>%
  select(total_tweets_clean) %>%
  slice(1)

total_tweets_fail<-twitter_notdei_summary %>%
  summarize(sum(fail_tweets))

min_perc<-round(min(twitter_notdei_summary$perc_fail),2)
max_perc<-round(max(twitter_notdei_summary$perc_fail),2)
```


```{r cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE}
knitr::opts_chunk$set(echo = FALSE)
nsf_div_grants<-read_csv("./error_analysis_bruna/validation_output/grants_nsf_diversity.csv",col_types = cols())
grant_dupes<-read_csv("./error_analysis_bruna/validation_output/grants_dupes.csv",col_types = cols())
grant_summary<-read_csv("./error_analysis_bruna/validation_output/grant_dupes_summary.csv",col_types = cols())

number_nsfdiv<-nrow(nsf_div_grants)


```


```{r cached=TRUE, echo = FALSE, warning=FALSE,message = FALSE}
knitr::opts_chunk$set(echo = FALSE)
gs_dupes<-read_csv("./error_analysis_bruna/validation_output/gs_dupes.csv",col_types = cols())
gs_sources<-read_csv("./error_analysis_bruna/validation_output/gs_sources_all_summary.csv",col_types = cols())
gs_sources_not_stem<-read_csv("./error_analysis_bruna/validation_output/gs_sources_not_stem_summary.csv",col_types = cols())

pm_sources_not_stem<-read_csv("./error_analysis_bruna/validation_output/pm_sources_not_stem_summary.csv",col_types = cols())
pm_dupes<-read_csv("./error_analysis_bruna/validation_output/pm_dupes.csv",col_types = cols())
pm_sources<-read_csv("./error_analysis_bruna/validation_output/pm_sources_all_summary.csv",col_types = cols())
pm_nondei<-read_csv("./error_analysis_bruna/validation_output/pm_nondei_examples.csv",col_types = cols())
gs_nondei<-read_csv("./error_analysis_bruna/validation_output/gs_neurology_examples.csv",col_types = cols())
pubs_dupes_summary<-read_csv("./error_analysis_bruna/validation_output/pubs_dupes_summary.csv",col_types = cols())

# nrow(pm_nondei)+nrow(gs_nondei)
```



\renewcommand{\arraystretch}{1}

\newpage
<!-- \blandscape -->


```{r Table1, echo=FALSE,message = FALSE,warning=FALSE}

Table1<-twitter_notdei_summary %>% 
  mutate(perc_fail=round(perc_fail,2)) %>% 
  select(-total_tweets_reviewed,-total_tweets_clean)

names(Table1)<-c("DEI Term","Irrelevant Tweets (N)","Total Tweets (N)","% Irrelevant")

Table1<-knitr::kable(Table1, 
      digits = 2,
      align="ccc",
      format="latex",
      row.names = FALSE,
      booktabs=T,
      longtable=F,
      linesep = "", #removes the blank line after every 5 lines
      caption = "Number of irrelevant tweets attributed by Goad and Chartwell to seven different DEI terms and the total number of tweets for each term in the original dataset.") %>%
     kable_styling(bootstrap_options = c("hover"),
                 full_width = T,
                 latex_options="scale_down",
                 font_size = 12,
                position = "left")  %>% 
    column_spec(column = 1, width = "7em") %>% 
  column_spec(column = 2, width = "12em") %>% 
    column_spec(column = 3, width = "12em") %>% 
  column_spec(column = 4, width = "12em")

  



Table1
```


```{=tex}
\newpage
\blandscape
```

```{r Table2, echo=FALSE,message = FALSE,warning=FALSE}

Table2<-twitter_notdei %>% 
  group_by(category) %>% 
  slice(1:5) %>% 
  rename("Tweet"="text",
         "Category"="category") %>% 
  group_by(Category) %>% 
  mutate(RNum=row_number()) %>% 
  relocate(RNum,.before=2) %>% 
  mutate(Category = ifelse(row_number()==1, Category, "")) %>% 
  select(Category,RNum,Tweet) %>% 
  # mutate(tweet=gsub("[[:punct:]]", "", tweet))  %>% 
 mutate(Tweet=str_sub(Tweet, 1, 110)) 



Table2$Tweet<-iconv(Table2$Tweet, "latin1", "ASCII", sub="")
# any(grepl("I_WAS_NOT_ASCII", iconv(Table2$Tweet, "latin1", "ASCII", sub="I_WAS_NOT_ASCII"))) 
# %>% 
#   mutate(text=gsub("\\\\", " ", tweet)
#                    
# Table1<-Tables[2]
# Table1<-as.data.frame(Table1)
# Table1<-arrange(Table1,desc(`APC..US..`))


names(Table2)<-c("DEI Term","No","sample irrelevant tweet")

Table2<-knitr::kable(Table2, 
      digits = 2,
      align="ccl",
      format="latex",
      row.names = FALSE,
      booktabs=T,
      longtable=F,
      linesep = "", #removes the blank line after every 5 lines
      caption = "A representative sample of tweets incorrectly attributed to different DEI terms.") %>%
  kable_styling(bootstrap_options = c("hover"),
                full_width = F,
                latex_options=c("scale_down",
                 "repeat_header"),
                font_size = 10,
               position = "left") %>% 
  column_spec(column = 1, width = "5em") %>% 
  column_spec(column = 2, width = "2em") %>% 
  column_spec(column = 3, width = "50em")

# %>%
#   footnote(number = c("OA Mirror title: Biochimie Open", "OA Mirror title: Micro and Nano Engineering")) %>% add_header_above(c(" " = 1, "Subscription Journal" = 2, "Mirror Journal" = 1))
# tmp<-str_replace(tmp, "Super1", "$^{1}$")
# tmp<-str_replace(tmp, "Super2", "$^{2}$")
# knitr::asis_output(tmp)
Table2
```


```{r Table3, echo=FALSE,message = FALSE,warning=FALSE}

Table3<-nsf_div_grants %>% 
  slice(1:20) %>% 
  select(title) %>% 
  rename("Grant Title"="title")  %>% 
  mutate(Sample=row_number()) %>% 
  relocate(Sample,.before=1)
 

Table3$`Grant Title`<-iconv(Table3$`Grant Title`, "latin1", "ASCII", sub="")
# any(grepl("I_WAS_NOT_ASCII", iconv(Table3$`Grant Title`, "latin1", "ASCII", sub="I_WAS_NOT_ASCII"))) 

 #  mutate(category = ifelse(row_number()==1, category, "")) %>% 
 #  select(category,tweet) %>% 
 #  # mutate(tweet=gsub("[[:punct:]]", "", tweet))  %>% 
 # mutate(tweet=str_sub(tweet, 1, 70))

# %>% 
#   mutate(text=gsub("\\\\", " ", tweet)
#                    
# Table1<-Tables[2]
# Table1<-as.data.frame(Table1)
# Table1<-arrange(Table1,desc(`APC..US..`))


# names(Table2)<-c("DEI Term","sample irrelevant tweet")

Table3<-knitr::kable(Table3, 
      digits = 2,
      align="cl",
      format="latex",
      row.names = FALSE,
      booktabs=T,
      # longtable=F,
      linesep = "", #removes the blank line after every 5 lines
      caption = "Sample non-DEI grants awarded by the NSF that were treated as 'DEI-Diversity' related by Goad and Chartwell. ") %>%
  kable_styling(bootstrap_options = c("hover"),
                full_width = T,
                latex_options="scale_down",
                font_size = 12,
               position = "left") %>% 
  column_spec(column = 1, width = "4em") %>% 
  column_spec(column = 2, width = "50em") 

# %>%
#   footnote(number = c("OA Mirror title: Biochimie Open", "OA Mirror title: Micro and Nano Engineering")) %>% add_header_above(c(" " = 1, "Subscription Journal" = 2, "Mirror Journal" = 1))
# tmp<-str_replace(tmp, "Super1", "$^{1}$")
# tmp<-str_replace(tmp, "Super2", "$^{2}$")
# knitr::asis_output(tmp)
Table3
```












```{=tex}
\newpage
\elandscape
```

```{r Table4, echo=FALSE,message = FALSE,warning=FALSE}
pm_sources_not_stem$Repository<-"PubMed"
gs_sources_not_stem$Repository<-"Google Scholar"
Table4<-bind_rows(gs_sources_not_stem,pm_sources_not_stem) %>% 
  relocate(Repository,.before=1) %>% 
  group_by(Repository) %>% 
  slice(1:20) %>% 
  mutate(Repository = ifelse(row_number()==1, Repository, "")) %>% 
  rename(Source=source,
         N=n) 
  

Table4$Source<-iconv(Table4$Source, "latin1", "ASCII", sub="")
# any(grepl("I_WAS_NOT_ASCII", iconv(Table4$Source, "latin1", "ASCII", sub="I_WAS_NOT_ASCII")))
# %>% 
#   mutate(gsub("[[:punct:]]", "", Title)) 
#  # mutate(tweet=str_sub(tweet, 1, 70))

# %>% 
#   mutate(text=gsub("\\\\", " ", tweet)
#                    
# Table1<-Tables[2]
# Table1<-as.data.frame(Table1)
# Table1<-arrange(Table1,desc(`APC..US..`))


# names(Table2)<-c("DEI Term","sample irrelevant tweet")

Table4<-knitr::kable(Table4, 
      digits = 2,
      align="clc",
      format="latex",
      row.names = FALSE,
      booktabs=T,
      # longtable=F,
      linesep = "", #removes the blank line after every 5 lines
      caption = "A sample of the non-STEM journals, and the number of articles from each, that were included in the NAS analysis of DEI-focused publications in STEM outlets.") %>%
  kable_styling(bootstrap_options = c("hover"),
                full_width = F,
                latex_options="scale_down",
                font_size = 10,
               position = "left") %>% 
  column_spec(column = 1, width = "8em") %>%
  column_spec(column = 2, width = "25em") %>% 
  column_spec(column = 3, width = "7em") 
  

# %>%
#   footnote(number = c("OA Mirror title: Biochimie Open", "OA Mirror title: Micro and Nano Engineering")) %>% add_header_above(c(" " = 1, "Subscription Journal" = 2, "Mirror Journal" = 1))
# tmp<-str_replace(tmp, "Super1", "$^{1}$")
# tmp<-str_replace(tmp, "Super2", "$^{2}$")
# knitr::asis_output(tmp)
Table4
```



```{=tex}
\newpage
\blandscape
```



<!-- \elandscape -->
<!-- \newpage -->

```{r Table5, echo=FALSE,message = FALSE,warning=FALSE}

gs_nondei$year<-as.numeric(gs_nondei$year)
pm_nondei$year<-as.numeric(pm_nondei$year)
Table5<-bind_rows(gs_nondei,pm_nondei) %>% 
  select(database,title, year,source) %>% 
  group_by(database) %>% 
   mutate(Sample=row_number()) %>% 
  relocate(Sample,.before=2) %>% 
  slice(1:10) %>% 
  rename("Repository"="database",
         Title=title,
         Source=source,
         Year=year)  %>% 
  mutate(Repository = ifelse(row_number()==1, Repository, "")) %>% 
  mutate(Title = gsub("[[:punct:]]", "", Title)) 

Table5$Title<-iconv(Table5$Title, "latin1", "ASCII", sub="")
# any(grepl("I_WAS_NOT_ASCII", iconv(Table5$Title, "latin1", "ASCII", sub="I_WAS_NOT_ASCII")))
 # mutate(tweet=str_sub(tweet, 1, 70))

# %>% 
#   mutate(text=gsub("\\\\", " ", tweet)
#                    
# Table1<-Tables[2]
# Table1<-as.data.frame(Table1)
# Table1<-arrange(Table1,desc(`APC..US..`))


# names(Table2)<-c("DEI Term","sample irrelevant tweet")

Table5<-knitr::kable(Table5, 
      digits = 2,
      align="cclcl",
      format="latex",
      row.names = FALSE,
      booktabs=T,
      longtable=F,
      linesep = "", #removes the blank line after every 5 lines
      caption = "Sample non-DEI publications incluyded by Goad and Chartwell in their analsyis of DEI-publications in STEM journals.") %>%
  kable_styling(bootstrap_options = c("hover"),
                full_width = T,
                latex_options="scale_down",
                font_size = 10,
               position = "left") %>% 
  column_spec(column = 1, width = "7em") %>%
  column_spec(column = 2, width = "4em") %>%
  column_spec(column = 3, width = "35em") %>% 
  column_spec(column = 4, width = "3em") %>%
  column_spec(column = 5, width = "13em")

# %>%
#   footnote(number = c("OA Mirror title: Biochimie Open", "OA Mirror title: Micro and Nano Engineering")) %>% add_header_above(c(" " = 1, "Subscription Journal" = 2, "Mirror Journal" = 1))
# tmp<-str_replace(tmp, "Super1", "$^{1}$")
# tmp<-str_replace(tmp, "Super2", "$^{2}$")
# knitr::asis_output(tmp)
Table5
```


```{=tex}
\elandscape
\newpage
```


